import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
=======
import TopBar from './components/TopBar';
import Header from './components/Header';
>>>>>>> 26ce4bc (first commit)

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>{children}</body>
=======
      <body className={inter.className}>
        <TopBar />
        <Header />
        {children}
        </body>
>>>>>>> 26ce4bc (first commit)
    </html>
  );
}
